main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logoutUser, name='logoutUser'),
    path('register/', views.registration_page, name='registration_page'),

]

quizzyfy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('student/', include('student.urls')),
    path('prof/', include('prof.urls')),
]

main/models/group.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

class Special_Students(models.Model):
    professor = models.ForeignKey(User, limit_choices_to={'groups__name': "Professor"}, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=10)
    students = models.ManyToManyField(User, limit_choices_to={'groups__name': "Student"}, related_name='student_groups')

    def __str__(self):
        return self.category_name


class Group_Form(ModelForm):
    class Meta:
        model = Special_Students
        fields = '__all__'
        exclude = ['professor']

prof/views/exam.py
from django.shortcuts import get_object_or_404, render, redirect
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden

def view_exams(request):
    prof = request.user

    new_Form = ExamForm()
    new_Form.fields["student_group"].queryset = Special_Students.objects.filter(
        professor=prof)
    new_Form.fields["question_paper"].queryset = Question_Paper.objects.filter(
        professor=prof)

    if request.method == 'POST':
        form = ExamForm(request.POST)
        if form.is_valid():
            exam = form.save(commit=False)
            exam.professor = prof
            exam.save()
            form.save_m2m()
            return redirect('prof:view_exams')

    exams = Exam_Model.objects.filter(professor=prof)

    return render(request, 'prof/exam/view_exams.html', {
        'exams': exams, 'examform': new_Form, 'prof': prof,
    })
    

def view_exam(request, exam_id):
    prof = request.user
    exam = Exam_Model.objects.get(professor=prof, pk=exam_id)
    return render(request, 'prof/exam/view_exam.html', {
        'exam': exam, 'prof': prof, 'student_group': exam.student_group.all()
    })
    

def edit_exam(request, exam_id):
    prof = request.user
    exam = get_object_or_404(Exam_Model, professor=prof, pk=exam_id)

    form = ExamForm(instance=exam)
    form.fields["student_group"].queryset = Special_Students.objects.filter(professor=prof)
    form.fields["question_paper"].queryset = Question_Paper.objects.filter(professor=prof)

    if request.method == 'POST':
        form = ExamForm(request.POST, instance=exam)
        if form.is_valid():
            form.save()
            return redirect('prof:view_exams')

    return render(request, 'prof/exam/edit_exam.html', {
        'examform': form,
        'exam': exam,
        'prof': prof
    })
    

def delete_exam(request, exam_id):
    prof = request.user
    exam = Exam_Model.objects.get(professor=prof, pk=exam_id)
    exam.delete()
    return redirect('prof:view_exams')

prof/views/group.py
from django.shortcuts import render, redirect
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden

def create_student_group(request):
    prof = request.user

    if request.method == "POST":
        form = Group_Form(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.professor = prof
            group.save()
            form.save_m2m()
            
            return redirect('prof:view_groups')

    return render(request, 'prof/group/addview_groups.html', {
        'special_students_db': Special_Students.objects.filter(professor=prof), 'prof': prof, 'groupForm': Group_Form()
    })
    

def view_specific_group(request, group_id):
    prof = request.user
    group = Special_Students.objects.get(professor=prof, pk=group_id)

    return render(request, 'prof/group/view_specific_group.html', {
        'group': group, 'prof': prof, 'group_students': group.students.all()
    })
    

def view_student_in_group(request, group_id):
    prof = request.user
    group = Special_Students.objects.get(professor=prof, pk=group_id)

    if request.method == 'POST':
        student_username = request.POST['username']
        student = User.objects.get(username=student_username)
        group.students.add(student)

    return render(request, 'prof/group/view_special_stud.html', {
        'students': group.students.all(), 'group': group, 'prof': prof
    })
    

def edit_group(request, group_id):
    prof = request.user
    group = Special_Students.objects.get(professor=prof, id=group_id)
    
    if request.method == "POST":
        form = Group_Form(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return redirect('prof:view_groups')

    form = Group_Form(instance=group)
    return render(request, 'prof/group/edit_group.html', {
        'group': group,
        'form': form,
        'prof': prof,
    })

def delete_group(request, group_id):
    prof = request.user
    group = Special_Students.objects.get(professor=prof, id=group_id)
    group.delete()
    return redirect('prof:view_groups')

prof/views/question.py
from django.shortcuts import get_object_or_404, render, redirect
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden
from django.contrib import messages


def add_question(request):
    prof = request.user

    if request.method == 'POST':
        form = QForm(request.POST)
        if form.is_valid():
            question_instance = form.save(commit=False)
            question_instance.professor = prof
            question_instance.save()
            messages.success(request, 'Question added successfully.')
            return redirect('prof:view_all_ques')
        else:
            messages.error(request, 'Error in the form submission. Please check the form.')

    return render(request, 'prof/question/question.html', {
        'question_db': Question_DB.objects.filter(professor=prof),
        'form': QForm(),
        'prof': prof
    })

   
def view_all_ques(request):
    prof = request.user

    if request.method == 'POST':
        Q_No = int(request.POST['qno'])
        sum_ = 1 + Question_DB.objects.filter(professor=prof).count()

        for i in range(Q_No+1, sum_):
            ques = Question_DB.objects.filter(
                professor=prof, qno=int(i)).first()
            ques.qno -= 1
            ques.save()

        sum_ -= 1

        Question_DB.objects.filter(professor=prof, qno=Q_No).delete()

    return render(request, 'prof/question/view_all_questions.html', {
        'question_db': Question_DB.objects.filter(professor=prof), 'prof': prof
    })

    
def edit_question(request, ques_qno):
    prof = request.user
    ques = Question_DB.objects.get(professor=prof, qno=ques_qno)
    
    if request.method == "POST":
        form = QForm(request.POST, instance=ques)
        if form.is_valid():
            form.save()
            return redirect('prof:view_all_ques')

    form = QForm(instance=ques)
    return render(request, 'prof/question/edit_question.html', {
        'ques': ques,
        'form': form,
        'prof': prof,
    })

prof/views/question_paper.py
from django.shortcuts import render, redirect
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden

def make_paper(request):
    prof = request.user

    if request.method == 'POST' and not request.POST.get('presence', False):
        add_question_in_paper(request)

    elif request.method == 'POST' and request.POST.get('presence', False):
        title = request.POST['title']
        Question_Paper.objects.filter(professor=prof, qPaperTitle=title).first().delete()

    return render(request, 'prof/question_paper/qpaper.html', {
        'qpaper_db': Question_Paper.objects.filter(professor=prof), 'prof': prof
    })



def add_question_in_paper(request):
    prof = request.user

    if request.method == 'POST' and request.POST.get('qpaper', False):
        paper_title = request.POST['qpaper']
        question_paper = Question_Paper(professor=prof, qPaperTitle=paper_title)
        question_paper.save()

        left_ques = []
        curr_paper_questions = question_paper.questions.all()
        for ques in Question_DB.objects.filter(professor=prof):
            if ques not in curr_paper_questions:
                left_ques.append(ques)

        return render(request, 'prof/question_paper/addquestopaper.html', {
            'qpaper': question_paper,
            'question_list': left_ques, 'prof': prof
        })

    elif request.method == 'POST' and request.POST.get('title', False):
        addques = request.POST['title']
        ques_ = Question_DB.objects.filter(professor=prof, qno=addques).first()
        title = request.POST['papertitle']
        ques_paper = Question_Paper.objects.filter(professor=prof, qPaperTitle=title).first()
        ques_paper.questions.add(ques_)
        ques_paper.save()

        left_ques = []
        curr_paper_questions = ques_paper.questions.all()
        for ques in Question_DB.objects.filter(professor=prof):
            if ques not in curr_paper_questions:
                left_ques.append(ques)

        return render(request, 'prof/question_paper/addquestopaper.html', {
            'qpaper': ques_paper, 'question_list': left_ques, 'prof': prof
        })

    return render(request, 'prof/question_paper/addquestopaper.html')



def view_paper(request):
    prof = request.user

    if request.method == 'POST':
        papertitle = request.POST['title']
        ques_paper = Question_Paper.objects.get(professor=prof, qPaperTitle=papertitle)

        return render(request, 'prof/question_paper/viewpaper.html', {
            'qpaper': ques_paper, 'question_list': ques_paper.questions.all(), 'prof': prof
        })



def edit_paper(request):
    prof = request.user

    if request.method == 'POST' and request.POST.get('title', False):
        papertitle = request.POST['title']
        ques_paper = Question_Paper.objects.filter(professor=prof, qPaperTitle=papertitle).first()

        left_ques = []
        curr_paper_questions = ques_paper.questions.all()
        for ques in Question_DB.objects.filter(professor=prof):
            if ques not in curr_paper_questions:
                left_ques.append(ques)

        return render(request, 'prof/question_paper/editpaper.html', {
            'ques_left': left_ques, 'qpaper': ques_paper, 'question_list': ques_paper.questions.all(), 'prof': prof
        })

    elif request.method == 'POST' and request.POST.get('remove', False):
        papertitle = request.POST['paper']
        no = request.POST['question']
        ques_paper = Question_Paper.objects.filter(professor=prof, qPaperTitle=papertitle).first()
        ques = Question_DB.objects.filter(professor=prof, qno=no).first()
        ques_paper.questions.remove(ques)
        ques_paper.save()

        left_ques = []
        curr_paper_questions = ques_paper.questions.all()
        for ques in Question_DB.objects.filter(professor=prof):
            if ques not in curr_paper_questions:
                left_ques.append(ques)

        return render(request, 'prof/question_paper/editpaper.html', {
            'ques_left': left_ques, 'qpaper': ques_paper, 'question_list': ques_paper.questions.all(), 'prof': prof
        })

    elif request.method == 'POST' and request.POST.get('qnumber', False) != False:
        qno = request.POST['qnumber']
        ptitle = request.POST['titlepaper']
        ques_paper = Question_Paper.objects.filter(
            professor=prof, qPaperTitle=ptitle).first()
        a = Question_DB.objects.filter(professor=prof, qno=qno).first()
        ques_paper.questions.add(a)
        ques_paper.save()

        left_ques = []
        curr_paper_questions = ques_paper.questions.all()
        for ques in Question_DB.objects.filter(professor=prof):
            if ques not in curr_paper_questions:
                left_ques.append(ques)

        return render(request, 'prof/question_paper/editpaper.html', {
            'ques_left': left_ques, 'qpaper': ques_paper, 'question_list': ques_paper.questions.all(), 'prof': prof
        })
            


def view_specific_paper(request, paper_id):
    prof = request.user

    paper = Question_Paper.objects.get(professor=prof, pk=paper_id)
    return render(request, 'prof/question_paper/viewpaper.html', {
        'qpaper': paper, 'question_list': paper.questions.all(), 'prof': prof
    })

prof/views/result.py
from django.shortcuts import render
from main.models.results import *
from student.models import StuExam_DB
from django.db.models import Avg

# def view_exam_scores(request, exam_id):
#     # Get the exam
#     #exam = StuExam_DB.objects.filter(pk=exam_id)
#     exam = StuExam_DB.objects.filter(pk=exam_id).values('examname')
#     first_exam = exam[0]  # Get the first dictionary from the queryset
#     examname = first_exam['examname']
#     print(exam)
#     students = StuExam_DB.objects.filter(examname=examname)
#     print(students)
#     #viewExam = StuExam_DB.objects.get(examname=exam.values('examname'), student=student)

#     # Get all scores for the exam
#     #scores = Score.objects.filter(exam=exam)

#     return render(request, 'prof/result/exam_scores.html', {'exam': exam, 'students': students})

def view_exam_scores(request, exam_id):
    # Get the exam
    exam = StuExam_DB.objects.filter(pk=exam_id).first()  # Use first() to get a single instance
    examname = exam.examname

    # Get all students for the exam
    students = StuExam_DB.objects.filter(examname=examname)

    # Calculate average score
    average_score = students.aggregate(Avg('score'))['score__avg']

    # Get top 5 scores
    top_scores = students.order_by('-score')[:5]

    # Get bottom 5 scores
    bottom_scores = students.order_by('score')[:5]

    context = {
        'exam': exam,
        'students': students,
        'average_score': average_score,
        'top_scores': top_scores,
        'bottom_scores': bottom_scores,
    }

    return render(request, 'prof/result/exam_scores.html', context)

def view_exam_results(request):
    # Retrieve all exams (adjust the filter conditions based on your model)
    #exams = Exam.objects.all()
    studentExamList = StuExam_DB.objects.filter(completed=1)

    context = {
        'exams': studentExamList,
        'prof': request.user,  # Assuming you have a user object representing the professor
    }

    return render(request, 'prof/result/exam_results.html', context)

prof/views/student.py
from django.shortcuts import render
from main.models import *
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden


def view_students(request):
    prof = request.user
    return render(request, 'prof/student/view_students.html', {
        'students': User.objects.filter(groups__name='Student'), 'prof': prof
    })
    

prof/templates/prof/group/addview_groups.html
{% extends 'prof/base/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Student Groups{% endblock title %}
{% block navbar_title %}{{ prof.username }}{% endblock navbar_title %}
{% block navitem_title %}Groups{% endblock navitem_title %}

{% block buttons %}
    <a class="btn btn-light" href="{% url 'prof:index' %}">Home</a> 
{% endblock buttons %}

{% block body %}
    <div class="container-fluid">
        <h3 class="alert alert-secondary my-1" align="center">Create a new group</h3>
        <div align='center' id="create_group">
            <div class="container d-flex h-100 row justify-content-center col-20">
                <form align='center' method="POST">
                    {% csrf_token %}
                    <!-- Manually render form fields -->
                    <label for="{{ groupForm.category_name.id_for_label }}">Category Name:</label>
                    {{ groupForm.category_name }}
                    <br>
                    
                    <label for="{{ groupForm.students.id_for_label }}">Students:</label>
                    {{ groupForm.students }}
                    <br>
                    <input class="btn btn-success" type="submit" value="Create">
                </form>
            </div>
        </div>
        <div id='groups'>
            <h1 class="alert alert-info my-3" align="center">Groups</h1>
            <form class="form-inline my-2 my-lg-0">
                <input id="searchGroup" class="form-control mr-sm-2" type="search" placeholder="Search Group"
                    aria-label="Search">
                    <a class="btn btn-dark" href="{% url 'prof:view_exams' %}" target="_blank">View Exams</a>
            </form>
            <div class="row">
                {% for group in special_students_db %}
                <div class="card my-3 mx-5 col-sm-3">
                    <h3 class="card-header">{{ group.category_name }}</h3>
                    <div class="card-body">
                        <p class="card-text">
                            <h4 class="card-subtitle mb-2 text-muted">Students</h4>
                            {% for stud in group.students.all %}
                            {{stud.username}}
                            {% endfor %}
                            <br><br>
                            <h4 class="card-subtitle mb-2 text-muted">Exams</h4>
                            {% for exam in group.exams.all %}
                                {{ exam.name }}
                                {% empty %}
                                    No exams associated
                            {% endfor %}
                        </p>
                        <a href="{% url 'prof:edit_group' group.id %}"
                            class="card-link btn btn-info">Edit</a>
                            <a href="{% url 'prof:delete_group' group.id %}" class="card-link btn btn-danger" 
                            onclick="return confirm('Are you sure you want to delete this group?')">Delete</a>
                    </div>
                </div>
                {% empty %}
                <h3>No groups</h3>
                {% endfor %}
            </div>
        </div>
    </div>
    <script src="{% static 'prof/js/groups.js' %}"></script>
{% endblock body %}

prof/templates/prof/group/delete_group.html
{% extends 'prof/base/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete Group{% endblock title %}
{% block navbar_title %}{{ prof.username }}{% endblock navbar_title %}
{% block navitem_title %}Delete Group{% endblock navitem_title %}

{% block buttons %}
    <a class="btn btn-warning mx-2" href="{% url 'prof:view_groups' %}">Cancel</a><br>
    <a class="btn btn-light" href="{% url 'prof:index' %}">Home</a>
{% endblock buttons %}

{% block body %}
    <div align='center' class="container-fluid">
        <div class="container d-flex h-100 row justify-content-center col-20">
            <p>Are you sure you want to delete the group "{{ group.category_name }}"?</p>
            <form method="post" action="{% url 'prof:delete_group' group_id=group.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </div>
{% endblock body %}

prof/templates/prof/group/edit_group.html
{% extends 'prof/base/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Group{% endblock title %}
{% block navbar_title %}{{ prof.username }}{% endblock navbar_title %}
{% block navitem_title %}Edit Group{% endblock navitem_title %}

{% block buttons %}
    <a class="btn btn-warning mx-2" href="{% url 'prof:view_groups' %}">Cancel</a><br>
    <a class="btn btn-light" href="{% url 'prof:index' %}">Home</a>
{% endblock buttons %}

{% block body %}
    <div align='center' class="container-fluid">
        <div class="container d-flex h-100 row justify-content-center col-20">
            <form method="post" action="{% url 'prof:edit_group' group_id=group.id %}">
                {% csrf_token %}
                
                <label for="{{ form.category_name.id_for_label }}">Category Name:</label>
                {{ form.category_name }}
                <br>
                
                <label for="{{ form.students.id_for_label }}">Students:</label>
                {{ form.students }}
                <br>
                
                <button type="submit">Update</button>
            </form>
        </div>
    </div>
{% endblock body %}

prof/templates/prof/group/view_special_stud.html
{% extends 'prof/base/base.html' %}

{% block title %}Students in group{% endblock title %}
{% block navbar_title %}Group: {{ group.category_name}}{% endblock navbar_title %}

{% block body %}
    <div class="container-fluid">
        <div>
            <h2>Add Student to group</h2>
            <form method="POST">
                {% csrf_token %}
                <h4>Username</h4>
                <input type="text" placeholder="Username" name="username">
                <input type="submit" value="Add">
            </form>
        </div>

        <div>
            <h3>Students:</h3><br>
            <ul>
                {% for student in students %}
                <li>{{student.username}}</li>
                {% empty %}
                <h4>No students in the group</h4>
                {% endfor %}
            </ul>
        </div>
    </div>


    <a class="btn btn-primary" href="{% url 'prof:view_specific_group' group.id %}">Go back to this group</a>
{% endblock body %}

prof/templates/prof/group/view_specific_group.html
{% extends 'prof/base/base.html' %}

{% block title %}About group{% endblock title %}
{% block navbar_title %}Group: {{ group.category_name }}{% endblock navbar_title %}

{% block buttons %}
    <a class="btn btn-light" href="{% url 'main:logoutUser' %}">Logout</a>
{% endblock buttons %}

{% block body %}
    <div class="container-fluid">
        <div align='center' id="group_students">
        <h2>Students in group</h2>
        <ul>
            {% for s in group_students %}
                <li>{{ s.username }}</li>
                {% empty %}
                    <h3>No students added in group</h3>
            {% endfor %}
        </ul>
    </div>
    </div>
    
    <a class="btn btn-primary mx-3 my-3" href="{% url 'prof:edit_group' group.id %}">Edit group</a><br>
    <a class="btn btn-primary mx-3 my-3" href="{% url 'prof:view_groups' %}">Go back to Groups</a>
{% endblock body %}