main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logoutUser, name='logoutUser'),
    path('register/', views.registration_page, name='registration_page'),

]

quizzyfy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('student/', include('student.urls')),
    path('prof/', include('prof.urls')),
]

main/models/exam.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from datetime import datetime
from .group import Special_Students
from .question_paper import Question_Paper

class Exam_Model(models.Model):
    professor = models.ForeignKey(User, limit_choices_to={'groups__name': "Professor"}, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    total_marks = models.IntegerField()
    duration = models.IntegerField()
    question_paper = models.ForeignKey(Question_Paper, on_delete=models.CASCADE, related_name='exams')
    student_group = models.ManyToManyField(Special_Students, related_name='exams')
    start_time = models.DateTimeField(default=datetime.now())
    end_time = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return self.name


class ExamForm(ModelForm):
    class Meta:
        model = Exam_Model
        exclude = ['professor']
    
    def __init__(self, *args, **kwargs):
        super(ExamForm, self).__init__(*args, **kwargs)
        # Customize form field attributes if needed
        self.fields['name'].label = 'Exam Name'
        self.fields['total_marks'].label = 'Total Marks'
        self.fields['duration'].label = 'Duration'
        self.fields['question_paper'].label = 'Question Paper'
        self.fields['student_group'].label = 'Student Group'
        self.fields['start_time'].label = 'Start Time'
        self.fields['end_time'].label = 'End Time'

main/models/group.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

class Special_Students(models.Model):
    professor = models.ForeignKey(User, limit_choices_to={'groups__name': "Professor"}, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=10)
    students = models.ManyToManyField(User, limit_choices_to={'groups__name': "Student"}, related_name='student_groups')

    def __str__(self):
        return self.category_name


class Group_Form(ModelForm):
    class Meta:
        model = Special_Students
        fields = '__all__'
        exclude = ['professor']

main/models/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_student = models.BooleanField(default=False)
    #is_professor = models.BooleanField(default=False)

main/models/question.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User

class Question_DB(models.Model):
    # added question number for help in question paper
    professor = models.ForeignKey(User, limit_choices_to={'groups__name': "Professor"}, on_delete=models.CASCADE, null=True)
    qno = models.AutoField(primary_key=True)
    question = models.CharField(max_length=100)
    optionA = models.CharField(max_length=100)
    optionB = models.CharField(max_length=100)
    optionC = models.CharField(max_length=100)
    optionD = models.CharField(max_length=100)
    answer = models.CharField(max_length=200)

    def __str__(self):
        return f'Question No.{self.qno}: {self.question} \t\t Options: \nA. {self.optionA} \nB.{self.optionB} \nC.{self.optionC} \nD.{self.optionD} '


class QForm(ModelForm):
    class Meta:
        model = Question_DB
        fields = '__all__'
        exclude = ['qno', 'professor']

main/models/question_paper.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from .question import Question_DB

class Question_Paper(models.Model):
    professor = models.ForeignKey(User, limit_choices_to={'groups__name': "Professor"}, on_delete=models.CASCADE)
    qPaperTitle = models.CharField(max_length=100)
    questions = models.ManyToManyField(Question_DB)

    def __str__(self):
        return f' Question Paper Title :- {self.qPaperTitle}\n'

main/models/results.py
from django.db import models
from django.contrib.auth.models import User

class Exam(models.Model):
    name = models.CharField(max_length=255)
    # Add other fields as needed

class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=5, decimal_places=2)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models.models import UserProfile

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserProfileForm(forms.ModelForm):
    is_student = forms.BooleanField(required=False, widget=forms.RadioSelect(choices=[(True, 'Student')]))
    is_professor = forms.BooleanField(required=False, widget=forms.RadioSelect(choices=[(True, 'Professor')]))

    class Meta:
        model = UserProfile
        fields = ['is_student','is_professor']

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm


from .forms import RegistrationForm, UserProfileForm

# Create your views here.
def index(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            
            if user.is_superuser or user.is_staff:
                return redirect('/admin')
            
            if user.groups.filter(name='Professor').exists():
                return redirect('prof:index')
            
            return redirect('student:index')
            

        return render(request, 'main/login.html', { 'wrong_cred_message': 'Error' })

    return render(request, 'main/login.html')


def logoutUser(request):
    logout(request)
    return render(request, 'main/logout.html',{ 'logout_message': 'Logged out Successfully' })

# def registration_page(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             # Log the user in after registration
#             login(request, user)
#             return redirect('home')  # Replace 'home' with the URL name of your home page
#     else:
#         form = UserCreationForm()

#     return render(request, 'main/registration_page.html', {'form': form})

def registration_page(request):
    if request.method == 'POST':
        user_form = RegistrationForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            # Log the user in after registration
            login(request, user)
            if profile.is_student:
                student_group = Group.objects.get(name='Student')  # Replace with your actual group name
                user.groups.add(student_group)
                return redirect('student:index')
            else:
                prof_group = Group.objects.get(name='Professor')  # Replace with your actual group name
                user.groups.add(prof_group)
                return redirect('prof:index')
    else:
        user_form = RegistrationForm()
        profile_form = UserProfileForm()

    return render(request, 'main/registration_page.html', {'user_form': user_form, 'profile_form': profile_form})

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/login.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    
    {% block body %}
    {% endblock body %}

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}Login{% endblock title %}

{% block body %}
    {% if wrong_cred_message %}
    <div class="alert alert-danger alert-dismissible" role="alert">
        <strong>{{ wrong_cred_message }}</strong> : Please enter correct credentials
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

    <div id="login">
        <h1 class="text-center text-black pt-5">Quizzyfy</h1>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post">
                            {% csrf_token %}
                            <div class="form-group" align='center'>
                                <h3><label for="username" class="text-info">Username:</label><br></h3>
                                <input type="text" name="username" id="username" class="form-control">
                            </div>
                            <div class="form-group" align='center'>
                                <h3><label for="password" class="text-info">Password:</label><br></h3>
                                <input type='password' name="password" id="password" class="form-control">
                            </div>
                            <div align='center' class="form-group">
                                <input type="submit" name="submit" class="btn btn-success btn-md" value="Login">
                            </div>
                            <div align='center' class="form-group">
                                <a href="{% url 'main:registration_page' %}" class="btn btn-info btn-md">Register</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock body %}

main/templates/main/logout.html
{% extends 'main/base.html' %}

{% block title %}Logout{% endblock title %}

{% block body %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ logout_message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <a href="{% url 'main:index' %}">Click here to Login</a>
{% endblock body %}

main/templates/main/registration_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
        crossorigin="anonymous">
    <link rel="stylesheet" href="/static/main/css/login.css">
    <title>Registration</title>
</head>

<body>
    <div id="registration">
        <h1 class="text-center text-black pt-5">Quizzyfy - Registration</h1>
        <div class="container">
            <div id="registration-row" class="row justify-content-center align-items-center">
                <div id="registration-column" class="col-md-6">
                    <div id="registration-box" class="col-md-12">
                        <form id="registration-form" class="form" method="post">
                            {% csrf_token %}
                            {{ user_form.as_p }}
                            {{ profile_form.as_p }}
                            
                            <!-- <div class="form-group">
                                <label for="{{ profile_form.is_student.id_for_label }}">Is Student:</label>
                                {{ profile_form.is_student }}
                            </div>
                            <div class="form-group">
                                <label for="{{ profile_form.is_professor.id_for_label }}">Is Professor:</label>
                                {{ profile_form.is_professor }}
                            </div> -->
                        
                            <div align='center' class="form-group">
                                <input type="submit" name="submit" class="btn btn-success btn-md" value="Register">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>